# Generated by Django 5.0 on 2023-12-18 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
